@echo off
REM Permanent Rust Build Environment Setup
REM ====================================
REM This script creates a permanent solution for VS toolchain conflicts

echo 🔧 Setting up permanent Rust build environment...
echo ================================================

REM Create build-tools directory if it doesn't exist
if not exist "build-tools" mkdir build-tools
cd build-tools

REM Create environment configuration file
echo @echo off > rust-env.bat
echo REM Rust Build Environment Configuration >> rust-env.bat
echo REM Generated by setup-rust-permanent.bat >> rust-env.bat
echo. >> rust-env.bat

REM Detect VS installations and add to config
echo REM Visual Studio Paths >> rust-env.bat
if exist "D:\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvarsall.bat" (
    echo set "VS_PATH=D:\Microsoft Visual Studio\18\Community" >> rust-env.bat
    echo ✅ Added VS2022 Community to config
) else if exist "C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" (
    echo set "VS_PATH=C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools" >> rust-env.bat
    echo ✅ Added VS Build Tools to config
)

REM Add Windows SDK path
echo set "WINDOWS_SDK=C:\Program Files (x86)\Windows Kits\10" >> rust-env.bat
echo set "SDK_VERSION=10.0.26100.0" >> rust-env.bat

REM Add Rust paths
echo set "RUST_PATH=C:\Users\Aomega Imaging\.cargo\bin" >> rust-env.bat
echo set "RUSTUP_TOOLCHAIN=stable-x86_64-pc-windows-msvc" >> rust-env.bat

echo. >> rust-env.bat
echo REM Setup build environment >> rust-env.bat
echo call "%%VS_PATH%%\VC\Auxiliary\Build\vcvarsall.bat" x64 >> rust-env.bat
echo set "PATH=%%VS_PATH%%\VC\Tools\MSVC\14.50.35717\bin\Hostx64\x64;%%RUST_PATH%%;%%PATH%%" >> rust-env.bat
echo set "LIB=%%WINDOWS_SDK%%\Lib\%%SDK_VERSION%%\um\x64;%%WINDOWS_SDK%%\Lib\%%SDK_VERSION%%\ucrt\x64;%%LIB%%" >> rust-env.bat
echo set "INCLUDE=%%WINDOWS_SDK%%\Include\%%SDK_VERSION%%\um;%%WINDOWS_SDK%%\Include\%%SDK_VERSION%%\ucrt;%%INCLUDE%%" >> rust-env.bat

echo ✅ Created rust-env.bat configuration

REM Create master build script
echo @echo off > build-rust.bat
echo REM Master Rust Build Script >> build-rust.bat
echo REM Usage: build-rust.bat [project-path] [optional: --release] >> build-rust.bat
echo. >> build-rust.bat

echo if "%%1"=="" ( >> build-rust.bat
echo     echo Usage: build-rust.bat [project-path] [optional: --release] >> build-rust.bat
echo     echo Example: build-rust.bat native\node_modules_cleaner --release >> build-rust.bat
echo     exit /b 1 >> build-rust.bat
echo ^) >> build-rust.bat

echo set "PROJECT_PATH=%%1" >> build-rust.bat
echo set "BUILD_TYPE=%%2" >> build-rust.bat

echo REM Load environment >> build-rust.bat
echo call rust-env.bat >> build-rust.bat

echo echo 🔧 Building Rust project: %%PROJECT_PATH%% >> build-rust.bat
echo. >> build-rust.bat

echo cd "%%PROJECT_PATH%%" >> build-rust.bat

echo if "%%BUILD_TYPE%%"=="--release" ( >> build-rust.bat
echo     cargo build --release >> build-rust.bat
echo ^) else ( >> build-rust.bat
echo     cargo build >> build-rust.bat
echo ^) >> build-rust.bat

echo if %%ERRORLEVEL%% equ 0 ( >> build-rust.bat
echo     echo ✅ Build successful! >> build-rust.bat
echo     if exist "target\release\*.exe" ( >> build-rust.bat
echo         echo 📦 Found release executables >> build-rust.bat
echo         dir target\release\*.exe >> build-rust.bat
echo     ^) >> build-rust.bat
echo ^) else ( >> build-rust.bat
echo     echo ❌ Build failed! >> build-rust.bat
echo ^) >> build-rust.bat

echo ✅ Created build-rust.bat master script

REM Create project-specific build script
echo @echo off > build-node-modules-cleaner.bat
echo REM Build Script for node_modules_cleaner >> build-node-modules-cleaner.bat
echo. >> build-node-modules-cleaner.bat
echo call build-rust.bat native\node_modules_cleaner --release >> build-node-modules-cleaner.bat
echo. >> build-node-modules-cleaner.bat
echo if exist "native\node_modules_cleaner\target\release\node_modules_cleaner.exe" ( >> build-node-modules-cleaner.bat
echo     echo 📦 Copying to bin directory... >> build-node-modules-cleaner.bat
echo     copy "native\node_modules_cleaner\target\release\node_modules_cleaner.exe" "bin\" >> build-node-modules-cleaner.bat
echo     echo ✅ Ready to use: bin\node_modules_cleaner.exe >> build-node-modules-cleaner.bat
echo ^) >> build-node-modules-cleaner.bat

echo ✅ Created build-node-modules-cleaner.bat

cd ..
echo.
echo 🎯 Permanent build solution created!
echo =================================
echo.
echo 📁 Created files in build-tools\:
echo   - rust-env.bat (environment configuration)
echo   - build-rust.bat (master build script)
echo   - build-node-modules-cleaner.bat (project-specific build)
echo.
echo 🚀 Usage:
echo   1. Quick build: build-node-modules-cleaner.bat
echo   2. Custom build: build-tools\build-rust.bat [path] [--release]
echo   3. Environment only: build-tools\rust-env.bat
echo.
echo 💡 This solution permanently fixes VS toolchain conflicts!