"""Agentic tool layer for the live progress dashboard.

This module gives an Ollama model with tool-calling support a safe, scoped
set of tools to *analyze screenshots*, *find issues*, and *make improvements*
without leaving the dashboard:

  * :data:`TOOLS` — the registry (name + description + JSON-schema parameters).
  * :func:`run_tool` — executes a single tool by name and returns a JSON result.
  * :func:`run_agent` — drives a multi-turn tool-calling loop against Ollama's
    ``/api/chat`` endpoint, executing every ``tool_calls`` entry and feeding the
    results back until the model stops requesting tools.

Tools are deliberately read-mostly. The only mutating tools are:

  * ``run_analysis`` / ``run_improvement_loop`` — launch the existing subprocess
    runners (which already refuse a second concurrent run) so the model can kick
    off work it cannot do itself.
  * ``update_issue`` — edit the shared issue tracker (``docs/issues.json``).
  * ``apply_edit`` — apply a *targeted* string replacement to a repo source file.
    It is gated behind an explicit ``auto_apply`` flag from the caller and a
    ``confirm: true`` argument from the model, writes a ``.bak`` backup, and
    appends an audit line to ``macro_logs/agent_edits.jsonl``. Edits outside the
    repository root (e.g. into ``macro_logs``) are rejected.

The module is import-safe: it never starts the HTTP server and only reaches for
Ollama when a tool/agent actually runs, so the dashboard server still boots even
if the Ollama client is unavailable.
"""

from __future__ import annotations

import base64
import io
import json
import os
import re
import sys
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

# --- path bootstrap so we can import the local shim and sibling helpers ------
HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent
for _p in (HERE, HERE.parent / "ux-pipeline" / "src"):
    _s = str(_p)
    if _s not in sys.path:
        sys.path.insert(0, _s)

try:
    from _ollama_client import OllamaClient  # local shim -> ux_pipeline client
except Exception:  # pragma: no cover - client import failure
    from ux_pipeline._ollama_client import OllamaClient  # type: ignore

from ux_server_lib import (
    _discover_roots,
    _build_issues_payload,
    _read_tracker,
    _write_tracker,
    _norm_status,
    _read_json,
    _safe_path,
    _get_store,
)
from ux_server_core import (
    _run_analysis,
    _run_status,
    _run_improvement_loop,
    _loop_status,
)

try:
    from PIL import Image
except Exception:  # pragma: no cover - PIL optional for dimensions
    Image = None

_AGENT_EDITS_LOG = "agent_edits.jsonl"
_DEFAULT_VISION_MODEL = os.getenv("VISION_MODEL") or "gemma4:e2b-it-qat"
_CLIENT_TIMEOUT_S = float(os.getenv("AGENT_OLLAMA_TIMEOUT", "600"))

# Mutable files (the analyzer / loop edit these). Edits are allowed there too,
# but never underneath macro_logs or outside the repo entirely.
_EDIT_ALLOWED_ROOTS = [REPO_ROOT]


# --------------------------------------------------------------------------- #
# Tool registry
# --------------------------------------------------------------------------- #
TOOLS: list[dict[str, Any]] = [
    {
        "type": "function",
        "function": {
            "name": "list_capture_sets",
            "description": (
                "List the screenshot capture sets available under the analysis root "
                "(macro_logs). Each entry has a relative name, an image count, and a "
                "modification time. Use this to discover which sets you can inspect "
                "with read_screenshot or analyze with run_analysis."
            ),
            "parameters": {
                "type": "object",
                "properties": {},
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "read_screenshot",
            "description": (
                "Look at one screenshot and return a text description suitable for a "
                "UX review. Returns the image dimensions plus (a) any stored "
                "vision/analysis preview from a previous run and (b) a fresh natural-"
                "language description generated by the vision model. Pass set (the "
                "capture-set relative name from list_capture_sets) and filename (the "
                "PNG basename). The model receives text, not pixels, so describe what "
                "you need in 'prompt'."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "set": {
                        "type": "string",
                        "description": "Capture-set relative name, e.g. "
                        "'2026-08-18__winui3-capture__ui-pages'.",
                    },
                    "filename": {
                        "type": "string",
                        "description": "Screenshot file basename, e.g. '01_dashboard.png'.",
                    },
                    "prompt": {
                        "type": "string",
                        "description": "What to look for (layout, controls, labels, "
                        "problems). Defaults to a general UX description.",
                    },
                },
                "required": ["set", "filename"],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "list_reports",
            "description": (
                "List stored UX analysis reports (from the SQLite store) filtered by "
                "optional model and/or screenshot set. Returns report metadata: key, "
                "set, model, status, timestamp, severity counts, issue/recommendation "
                "totals."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "limit": {"type": "integer", "description": "Max rows (default 20)."},
                    "model": {"type": "string", "description": "Filter by model name."},
                    "set": {"type": "string", "description": "Filter by screenshot set."},
                },
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "read_report",
            "description": (
                "Read a full stored analysis report. Pass report_key (from "
                "list_reports) or omit it to read the most recent report. Returns the "
                "per-screenshot findings, consolidated summary, and code "
                "recommendations."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "report_key": {
                        "type": "string",
                        "description": "Report key; omit for the latest report.",
                    },
                },
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "find_issues",
            "description": (
                "Search the shared issue tracker (docs/issues.json). Filter by status, "
                "category, severity, and/or a free-text query. Returns matching issues "
                "with their id, title, severity, status, notes, and source metadata."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "status": {
                        "type": "string",
                        "enum": ["open", "in_progress", "blocked", "pending", "done",
                                 "wontfix"],
                        "description": "Filter by status.",
                    },
                    "category": {"type": "string", "description": "Filter by category."},
                    "severity": {
                        "type": "string",
                        "enum": ["critical", "high", "medium", "low"],
                        "description": "Filter by severity.",
                    },
                    "q": {"type": "string", "description": "Free-text search."},
                    "limit": {"type": "integer", "description": "Max rows (default 50)."},
                },
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "read_issue",
            "description": "Read one issue from the tracker by its issue_id.",
            "parameters": {
                "type": "object",
                "properties": {
                    "issue_id": {"type": "string", "description": "The issue id."},
                },
                "required": ["issue_id"],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "update_issue",
            "description": (
                "Update an issue's status and/or resolution note in the shared tracker. "
                "Use this after resolving or triaging an issue found during analysis."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "issue_id": {"type": "string", "description": "The issue id."},
                    "status": {
                        "type": "string",
                        "enum": ["open", "in_progress", "blocked", "pending", "done",
                                 "wontfix"],
                        "description": "New status.",
                    },
                    "resolution": {
                        "type": "string",
                        "description": "Optional resolution note.",
                    },
                },
                "required": ["issue_id"],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "analysis_status",
            "description": (
                "Return the current analyzer and self-improvement loop status (running "
                "/ finished / idle, PIDs, recent log tails). Use to check whether a "
                "run or loop you started is still going."
            ),
            "parameters": {
                "type": "object",
                "properties": {},
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "run_analysis",
            "description": (
                "Launch a full UX screenshot analysis on a capture set (or the latest "
                "auto-detected set) as a subprocess. Returns immediately with the run "
                "pid; poll analysis_status to track progress. Refuses to start a second "
                "concurrent run."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "set": {
                        "type": "string",
                        "description": "Capture-set relative name; omit for latest.",
                    },
                    "model": {
                        "type": "string",
                        "description": "Vision model to use (optional).",
                    },
                },
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "run_improvement_loop",
            "description": (
                "Launch the self-improvement loop, which works through open issues in "
                "docs/issues.json, generates a fix per issue, and verifies it. Refuses a "
                "second concurrent loop. Use dry_run=true to preview the plan without "
                "editing files."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "model": {"type": "string", "description": "Model for fixes (optional)."},
                    "category": {"type": "string", "description": "Limit to one category."},
                    "max_iterations": {
                        "type": "integer",
                        "description": "Max loop iterations (default 3).",
                    },
                    "dry_run": {
                        "type": "boolean",
                        "description": "Preview only, no file edits (default false).",
                    },
                },
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "read_file",
            "description": (
                "Read a repository source file (read-only) so you can inspect code "
                "before proposing an improvement. Path is relative to the repo root. "
                "Optionally return a line range. Large files are truncated."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "path": {
                        "type": "string",
                        "description": "Repo-relative path, e.g. 'gui-winui/SpaceAnalyzer/"
                        "ViewModels/ScanViewModel.cs'.",
                    },
                    "start": {"type": "integer", "description": "1-based start line."},
                    "end": {"type": "integer", "description": "1-based end line (inclusive)."},
                    "max_lines": {
                        "type": "integer",
                        "description": "Cap returned lines when no range given (default 400).",
                    },
                },
                "required": ["path"],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "search_code",
            "description": (
                "Search the repository for a regex pattern (case-insensitive) and return "
                "matching file:line snippets. Use to locate the code behind a UI issue "
                "before proposing an edit. Restricted to the repo root."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "pattern": {"type": "string", "description": "Regex to search for."},
                    "path": {
                        "type": "string",
                        "description": "Repo-relative path/glob to scope the search "
                        "(optional, e.g. 'gui-winui').",
                    },
                    "max": {"type": "integer", "description": "Max matches (default 40)."},
                },
                "required": ["pattern"],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "apply_edit",
            "description": (
                "Apply a targeted, single string replacement to a repo source file to "
                "make an improvement. REQUIRES confirm=true and an enabled 'allow edits' "
                "session. A .bak backup is written and every change is audited to "
                "macro_logs/agent_edits.jsonl. Prefer the smallest unique old_string; set "
                "replace_all=true to change every occurrence. Edits outside the repo root "
                "are rejected."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "path": {
                        "type": "string",
                        "description": "Repo-relative path to the file to edit.",
                    },
                    "old_string": {
                        "type": "string",
                        "description": "Exact text to replace (must appear verbatim).",
                    },
                    "new_string": {
                        "type": "string",
                        "description": "Replacement text.",
                    },
                    "confirm": {
                        "type": "boolean",
                        "description": "Must be true to authorize the edit.",
                    },
                    "replace_all": {
                        "type": "boolean",
                        "description": "Replace every occurrence (default false).",
                    },
                },
                "required": ["path", "old_string", "new_string", "confirm"],
                "additionalProperties": False,
            },
        },
    },
]


def list_tool_schemas() -> list[dict[str, Any]]:
    """Return the tool catalog (the ``function`` payloads) for the UI / Ollama."""
    return [t["function"] for t in TOOLS]


# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
_CLIENT_LOCK = threading.Lock()
_CLIENT: OllamaClient | None = None


def _client() -> OllamaClient:
    global _CLIENT
    with _CLIENT_LOCK:
        if _CLIENT is None:
            _CLIENT = OllamaClient(timeout=_CLIENT_TIMEOUT_S)
    return _CLIENT


def list_ollama_models() -> list[str]:
    """Return installed Ollama model names (best-effort)."""
    try:
        models = _client().list_models()
    except Exception:
        return []
    out: list[str] = []
    for m in models:
        if isinstance(m, dict) and m.get("name"):
            out.append(str(m["name"]))
    return out


def _model_supports_tools(name: str) -> bool:
    """Heuristic: does this model family do Ollama native tool calling?"""
    n = (name or "").lower()
    if "embed" in n:
        return False
    for k in (
        "qwen3", "qwen2.5", "qwen2", "llama3", "llama-3", "deepseek", "mistral",
        "mixtral", "gemma2", "gemma3", "gemma4", "qwq", "phi4", "phi-4",
        "command-r", "nemotron", "codellama", "llama3.1", "llama3.2", "llama3.3",
    ):
        if k in n:
            return True
    return False


def _model_is_vision(name: str) -> bool:
    """Heuristic: can this model accept image input?"""
    n = (name or "").lower()
    for k in (
        "vl", "vision", "llava", "moondream", "minicpm-v", "minicpmv", "cogvlm",
        "glm-4v", "internvl", "qwen-vl", "gemma4",
    ):
        if k in n:
            return True
    return False


# Preferred models for the agent's main tool-calling chat, in order. The first
# installed one wins; this keeps the "Default" model button useful without the
# user having to know which coding models are pulled.
_CHAT_MODEL_PREFS = [
    "qwen3:8b", "qwen3:4b", "qwen3:latest", "qwen3", "qwen3-vl:4b",
    "qwen3-vl:2b", "deepseek-r1:7b", "llama3.2:3b",
]
# Vision models for read_screenshot / analyzer runs, most-capable first.
_VISION_MODEL_PREFS = [
    "qwen3-vl:4b", "qwen3-vl:2b", "gemma4:e2b-it-qat", "llama3.2-vision",
]


def select_chat_model(requested: str | None = None) -> str:
    """Pick a model for the agent's tool-calling loop.

    If the caller named a model we honor it (even if not currently installed —
    Ollama will surface a clear "not found" error rather than silently swapping).
    Otherwise we route to the best *installed* tool-capable model, falling back
    to any installed model, then a sane hardcoded default.
    """
    if requested and requested.strip():
        return requested.strip()
    models = list_ollama_models()
    installed = set(models)
    for p in _CHAT_MODEL_PREFS:
        if p in installed:
            return p
    tool_models = [m for m in models if _model_supports_tools(m)]
    if tool_models:
        return tool_models[0]
    if models:
        return models[0]
    return "qwen3:latest"


def select_vision_model(requested: str | None = None) -> str:
    """Pick a vision model for screenshot description / analysis runs."""
    if requested and requested.strip():
        return requested.strip()
    models = list_ollama_models()
    installed = set(models)
    for p in _VISION_MODEL_PREFS:
        if p in installed:
            return p
    vision = [m for m in models if _model_is_vision(m)]
    if vision:
        return vision[0]
    # Known-good vision default even if not yet pulled (Ollama will fetch/error).
    return "gemma4:e2b-it-qat"


def _resolve_repo_file(repo_root: Path, path: str) -> Path | None:
    """Resolve a repo-relative path, ensuring it stays inside the repo root."""
    try:
        p = (repo_root / path)
        if p.is_absolute():
            p = p
        p = p.resolve()
        p.relative_to(repo_root.resolve())
    except (OSError, ValueError):
        return None
    return p


# --------------------------------------------------------------------------- #
# Tool executors
# --------------------------------------------------------------------------- #
def _tool_list_capture_sets(args: dict, ctx: dict) -> dict:
    return {"sets": _discover_roots(ctx["root_base"])}


def _tool_read_screenshot(args: dict, ctx: dict) -> dict:
    root_base: Path = ctx["root_base"]
    set_rel = (args.get("set") or "").strip()
    filename = (args.get("filename") or "").strip()
    if not set_rel or not filename:
        return {"ok": False, "error": "set and filename are required"}
    safe_name = Path(filename).name
    base = _safe_path(root_base, set_rel)
    if base is None or not base.is_dir():
        return {"ok": False, "error": f"unknown capture set: {set_rel}"}
    img = base / safe_name
    if not img.is_file():
        # fall back to a recursive search so the caller need not know subfolders
        hits = sorted(base.rglob(safe_name))
        if not hits:
            return {"ok": False, "error": f"screenshot not found: {safe_name}"}
        img = hits[0]
    try:
        data = img.read_bytes()
    except OSError as exc:
        return {"ok": False, "error": f"cannot read image: {exc}"}
    w = h = None
    try:
        if Image is not None:
            with Image.open(io.BytesIO(data)) as im:
                w, h = im.size
    except Exception:
        pass

    # Surface any stored previews from a live/prior run for this key.
    previews: dict[str, str] = {}
    progress = _read_json(root_base / "analysis_progress.json") or {}
    shots = progress.get("shots") or {}
    key = img.relative_to(root_base).as_posix()
    shot = shots.get(key) or {}
    if isinstance(shot, dict):
        vp = shot.get("vision_preview")
        ap = shot.get("analysis_preview")
        if vp:
            previews["stored_vision_preview"] = vp
        if ap:
            previews["stored_analysis_preview"] = ap

    # Fresh vision description (text) so the model can actually "see" the shot.
    prompt = (args.get("prompt") or "").strip() or (
        "Describe this UI screenshot for a UX review: identify the screen, "
        "visible panels, headings, buttons, inputs, and any obvious layout, "
        "contrast, alignment, or clarity problems."
    )
    vision_model = select_vision_model(ctx.get("vision_model"))
    description = ""
    try:
        description = _client().generate(
            vision_model, prompt, images=[data], think=False, stream=False,
        )
    except Exception as exc:  # vision model may be unavailable; degrade gracefully
        description = f"(vision describe failed: {exc})"
    return {
        "ok": True,
        "path": key,
        "width": w,
        "height": h,
        "size_bytes": len(data),
        "description": description,
        **previews,
    }


def _tool_list_reports(args: dict, ctx: dict) -> dict:
    store = _get_store(ctx["root_base"])
    if store is None:
        return {"ok": False, "status": "unavailable", "error": "reports db missing"}
    try:
        limit = int(args.get("limit") or 20)
    except (TypeError, ValueError):
        limit = 20
    rows = store.list_reports(
        limit=limit, model=args.get("model"), screenshot_set=args.get("set"),
    )
    return {"ok": True, "count": len(rows), "reports": rows}


def _tool_read_report(args: dict, ctx: dict) -> dict:
    store = _get_store(ctx["root_base"])
    if store is None:
        return {"ok": False, "status": "unavailable", "error": "reports db missing"}
    key = (args.get("report_key") or "").strip() or None
    rep = store.get(key) if key else store.get_latest()
    if rep is None:
        return {"ok": False, "error": "no report found"}
    payload = rep.get("report") or {}
    payload["_meta"] = {
        k: rep.get(k)
        for k in ("id", "report_key", "screenshot_set", "model", "status",
                  "timestamp", "num_issues", "num_recommendations", "severity_counts")
    }
    return {"ok": True, "report": payload}


def _tool_find_issues(args: dict, ctx: dict) -> dict:
    try:
        limit = int(args.get("limit") or 50)
    except (TypeError, ValueError):
        limit = 50
    return _build_issues_payload(
        status=(args.get("status") or "").strip() or None,
        category=(args.get("category") or "").strip() or None,
        severity=(args.get("severity") or "").strip() or None,
        q=(args.get("q") or "").strip() or None,
        limit=limit,
    )


def _tool_read_issue(args: dict, ctx: dict) -> dict:
    issue_id = (args.get("issue_id") or "").strip()
    if not issue_id:
        return {"ok": False, "error": "issue_id required"}
    data = _read_tracker()
    for it in data.get("issues", []):
        if it.get("issue_id") == issue_id:
            return {"ok": True, "issue": it}
    return {"ok": False, "error": "issue not found"}


def _tool_update_issue(args: dict, ctx: dict) -> dict:
    issue_id = (args.get("issue_id") or "").strip()
    new_status = (args.get("status") or "").strip()
    resolution = (args.get("resolution") or "").strip()
    if not issue_id:
        return {"ok": False, "error": "issue_id required"}
    data = _read_tracker()
    found = None
    for it in data.get("issues", []):
        if it.get("issue_id") == issue_id:
            found = it
            break
    if found is None:
        return {"ok": False, "error": "issue not found"}
    if new_status:
        found["status"] = _norm_status(new_status)
    found["last_seen"] = datetime.now(timezone.utc).isoformat(timespec="seconds")
    if resolution:
        extra = found.get("extra")
        if not isinstance(extra, dict):
            extra = {}
            found["extra"] = extra
        extra["resolution"] = resolution
    _write_tracker(data)
    return {"ok": True, "issue": found}


def _tool_analysis_status(args: dict, ctx: dict) -> dict:
    root_base: Path = ctx["root_base"]
    return {
        "analysis": _run_status(root_base),
        "loop": _loop_status(root_base),
    }


def _tool_run_analysis(args: dict, ctx: dict) -> dict:
    model = (args.get("model") or "").strip() or select_vision_model(ctx.get("vision_model"))
    return _run_analysis(
        ctx["root_base"],
        model=model,
        set_name=(args.get("set") or "").strip() or None,
    )


def _tool_run_loop(args: dict, ctx: dict) -> dict:
    mi = args.get("max_iterations")
    if mi is not None:
        try:
            mi = int(mi)
        except (TypeError, ValueError):
            mi = None
    dr = args.get("dry_run")
    if isinstance(dr, str):
        dr = dr.strip().lower() in ("1", "true", "yes", "on")
    else:
        dr = bool(dr)
    model = (args.get("model") or "").strip() or select_chat_model()
    return _run_improvement_loop(
        ctx["root_base"],
        model=model,
        max_iterations=mi,
        category=(args.get("category") or "").strip() or None,
        dry_run=dr,
    )


def _tool_read_file(args: dict, ctx: dict) -> dict:
    path = (args.get("path") or "").strip()
    p = _resolve_repo_file(ctx["repo_root"], path)
    if p is None or not p.is_file():
        return {"ok": False, "error": "file not found in repo or outside root"}
    try:
        text = p.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        return {"ok": False, "error": f"cannot read: {exc}"}
    lines = text.splitlines()
    start = args.get("start")
    end = args.get("end")
    if start is None and end is None:
        max_lines = int(args.get("max_lines") or 400)
        if len(lines) > max_lines:
            head = lines[:max_lines]
            return {
                "ok": True,
                "path": path,
                "total_lines": len(lines),
                "truncated": True,
                "note": f"showing first {max_lines} of {len(lines)} lines",
                "content": "\n".join(head),
            }
        return {"ok": True, "path": path, "total_lines": len(lines), "content": text}
    try:
        s = max(1, int(start)) if start is not None else 1
        e = int(end) if end is not None else len(lines)
    except (TypeError, ValueError):
        return {"ok": False, "error": "start/end must be integers"}
    s = max(1, s)
    e = min(len(lines), e)
    return {
        "ok": True,
        "path": path,
        "start": s,
        "end": e,
        "total_lines": len(lines),
        "content": "\n".join(lines[s - 1:e]),
    }


def _tool_search_code(args: dict, ctx: dict) -> dict:
    pattern = (args.get("pattern") or "").strip()
    if not pattern:
        return {"ok": False, "error": "pattern required"}
    try:
        rx = re.compile(pattern, re.IGNORECASE)
    except re.error as exc:
        return {"ok": False, "error": f"invalid regex: {exc}"}
    scope = (args.get("path") or "").strip()
    max_matches = int(args.get("max") or 40)
    repo_root: Path = ctx["repo_root"]
    if scope:
        base = _resolve_repo_file(repo_root, scope)
        if base is None:
            return {"ok": False, "error": "invalid scope path"}
        roots = [base]
    else:
        roots = [repo_root]
    # Skip noisy / build / vcs dirs.
    skip = {".git", "target", "bin", "obj", "__pycache__", "node_modules",
            ".venv", "venv", "ux_reports.db-journal", "ux_reports.db-wal"}
    matches: list[dict[str, str]] = []
    for root in roots:
        for f in root.rglob("*"):
            if not f.is_file():
                continue
            rel = f.relative_to(repo_root).as_posix()
            if any(part in skip for part in f.parts):
                continue
            if f.suffix.lower() in (".png", ".jpg", ".jpeg", ".gif", ".bmp",
                                    ".webp", ".ico", ".db", ".sqlite", ".zip",
                                    ".exe", ".dll"):
                continue
            if len(matches) >= max_matches:
                break
            try:
                lines = f.read_text(encoding="utf-8", errors="ignore").splitlines()
            except OSError:
                continue
            for i, ln in enumerate(lines, 1):
                if rx.search(ln):
                    matches.append({"file": rel, "line": i, "text": ln.strip()[:300]})
                    if len(matches) >= max_matches:
                        break
    return {"ok": True, "count": len(matches), "pattern": pattern, "matches": matches}


def _tool_apply_edit(args: dict, ctx: dict, auto_apply: bool = False) -> dict:
    if not auto_apply:
        return {
            "ok": False,
            "error": "Edits are disabled for this session. Enable 'Allow code "
                     "edits' in the dashboard (or pass auto_apply=true) and resend.",
        }
    confirm = args.get("confirm")
    if isinstance(confirm, str):
        confirm = confirm.strip().lower() in ("1", "true", "yes", "on")
    if not confirm:
        return {"ok": False, "error": "confirm=true is required to apply an edit"}
    path = (args.get("path") or "").strip()
    old = args.get("old_string")
    new = args.get("new_string")
    if not path or old is None or new is None:
        return {"ok": False, "error": "path, old_string, new_string are required"}
    p = _resolve_repo_file(ctx["repo_root"], path)
    if p is None or not p.is_file():
        return {"ok": False, "error": "file not found in repo or outside root"}
    try:
        text = p.read_text(encoding="utf-8")
    except OSError as exc:
        return {"ok": False, "error": f"cannot read: {exc}"}
    replace_all = bool(args.get("replace_all"))
    if replace_all:
        if old not in text:
            return {"ok": False, "error": "old_string not found in file"}
        count = text.count(old)
        updated = text.replace(old, new)
    else:
        idx = text.find(old)
        if idx == -1:
            return {"ok": False, "error": "old_string not found (verbatim) in file"}
        count = 1
        updated = text[:idx] + new + text[idx + len(old):]
    # Backup before mutating.
    bak = p.with_suffix(p.suffix + ".bak")
    try:
        bak.write_text(text, encoding="utf-8")
    except OSError:
        pass
    try:
        p.write_text(updated, encoding="utf-8")
    except OSError as exc:
        return {"ok": False, "error": f"write failed: {exc}"}
    # Audit line.
    log_path = ctx["root_base"] / _AGENT_EDITS_LOG
    entry = {
        "ts": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "path": path,
        "replace_all": replace_all,
        "count": count,
        "backup": bak.name,
    }
    try:
        with log_path.open("a", encoding="utf-8") as lf:
            lf.write(json.dumps(entry, ensure_ascii=False) + "\n")
    except OSError:
        pass
    return {
        "ok": True,
        "path": path,
        "replacements": count,
        "backup": bak.name,
        "note": "Edit applied. Use the self-improvement loop or a build to verify.",
    }


_DISPATCH: dict[str, Callable[..., dict]] = {
    "list_capture_sets": _tool_list_capture_sets,
    "read_screenshot": _tool_read_screenshot,
    "list_reports": _tool_list_reports,
    "read_report": _tool_read_report,
    "find_issues": _tool_find_issues,
    "read_issue": _tool_read_issue,
    "update_issue": _tool_update_issue,
    "analysis_status": _tool_analysis_status,
    "run_analysis": _tool_run_analysis,
    "run_improvement_loop": _tool_run_loop,
    "read_file": _tool_read_file,
    "search_code": _tool_search_code,
    "apply_edit": _tool_apply_edit,
}


def run_tool(name: str, args: dict | None, ctx: dict,
             auto_apply: bool = False) -> dict:
    """Execute a single tool by name and return a JSON-serializable result.

    Failures are returned as ``{"ok": False, "error": ...}`` rather than raised,
    so the agent loop can feed the error back to the model as a normal tool result.
    """
    if not isinstance(args, dict):
        args = {}
    fn = _DISPATCH.get(name)
    if fn is None:
        return {"ok": False, "error": f"unknown tool: {name}"}
    try:
        if name == "apply_edit":
            return fn(args, ctx, auto_apply=auto_apply)
        return fn(args, ctx)
    except Exception as exc:  # never let a tool crash the agent/server
        return {"ok": False, "error": f"{type(exc).__name__}: {exc}"}


# --------------------------------------------------------------------------- #
# Agent loop
# --------------------------------------------------------------------------- #
AGENT_SYSTEM = (
    "You are a UX analysis and self-improvement assistant for the Space Analyzer "
    "desktop app. You help the user analyze screenshots, find issues, and make "
    "improvements using the tools available to you.\n\n"
    "Workflow:\n"
    "1. To analyze screenshots, call list_capture_sets, then read_screenshot(set, "
    "filename) for each screen you care about. read_screenshot returns a TEXT "
    "description (you receive text, not pixels), plus any stored vision/analysis "
    "previews.\n"
    "2. To find issues, use find_issues (filter by status/category/severity) or "
    "read_report to review a prior full analysis. Cross-check what you see in a "
    "screenshot against stored reports and issues so you do not re-report known "
    "problems.\n"
    "3. To make improvements, inspect the code with read_file / search_code, then "
    "propose a change with apply_edit (a small, unique old_string -> new_string). "
    "apply_edit requires confirm=true and an enabled edits session, writes a .bak "
    "backup, and is audited. Prefer the smallest safe change. For multi-issue or "
    "verified fixes, run_improvement_loop is available.\n\n"
    "Be concise. When you finish, summarize what you found and the concrete "
    "improvements you made or recommend. Do not invent tools or file paths; verify "
    "with the tools before claiming something."
)


def _coerce_tool_args(raw: Any) -> dict:
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str):
        try:
            parsed = json.loads(raw)
            if isinstance(parsed, dict):
                return parsed
        except (json.JSONDecodeError, ValueError):
            pass
    return {}


def _extract_assistant_text(msg: Any) -> str:
    """Pull the assistant's user-visible text out of an Ollama ``message``.

    Some models (notably qwen3-vl) stream their reasoning into a ``thinking``
    field even when ``think=False``, leaving ``content`` empty. If ``content``
    is blank we fall back to the cleaned ``thinking`` text so the agent loop
    and the user still get a usable answer. A leading ``<think>…</think>``
    block (occasionally embedded in ``content``) is stripped either way.
    """
    if not isinstance(msg, dict):
        return ""
    text = msg.get("content") or ""
    if not text:
        th = msg.get("thinking") or ""
        if th:
            text = re.sub(r"</?think>", "", th, flags=re.I).strip()
    if "<think>" in text:
        text = re.sub(r"<think>.*?</think>", "", text, flags=re.S | re.I).strip()
    return text


def run_agent(user_message: str, model: str, ctx: dict, *,
              history: list[dict] | None = None,
              max_iterations: int = 6, auto_apply: bool = False) -> dict:
    """Run a tool-calling agent loop against Ollama and return the transcript.

    Returns ``{"answer", "transcript", "iterations", "model", "error?"}``.
    ``transcript`` is a list of steps: assistant turns (with optional tool_calls)
    and tool-result turns (name/args/result) for the UI to render.
    """
    tools_schema = list_tool_schemas()
    client = _client()
    # Route the chat model: an explicit, non-empty model is honored as-is; an
    # empty one ("Default") is sent to the best installed tool-capable model.
    model = select_chat_model(model)
    messages: list[dict[str, Any]] = [{"role": "system", "content": AGENT_SYSTEM}]
    for h in (history or []):
        if isinstance(h, dict) and h.get("role") in ("user", "assistant"):
            messages.append({
                "role": h["role"],
                "content": str(h.get("content", "")),
            })
    messages.append({"role": "user", "content": user_message})

    transcript: list[dict[str, Any]] = []
    last_answer = ""
    iterations = 0
    try:
        for i in range(max(1, int(max_iterations))):
            iterations = i + 1
            msg = client.chat_with_tools(
                model, messages, tools_schema, think=False,
                options={"num_ctx": 8192},
            )
            content = _extract_assistant_text(msg)
            tool_calls = msg.get("tool_calls") or []
            assistant_step: dict[str, Any] = {
                "role": "assistant",
                "content": content,
                "tool_calls": tool_calls,
            }
            messages.append({
                "role": "assistant",
                "content": content,
                **({"tool_calls": tool_calls} if tool_calls else {}),
            })
            transcript.append(assistant_step)
            if not tool_calls:
                last_answer = content
                break
            for tc in tool_calls:
                fn = tc.get("function", {}) if isinstance(tc, dict) else {}
                name = fn.get("name", "")
                args = _coerce_tool_args(fn.get("arguments"))
                result = run_tool(name, args, ctx, auto_apply=auto_apply)
                transcript.append({
                    "role": "tool",
                    "name": name,
                    "args": args,
                    "result": result,
                })
                messages.append({
                    "role": "tool",
                    "content": json.dumps(result, ensure_ascii=False, default=str),
                    "name": name,
                })
            last_answer = content
    except Exception as exc:
        return {
            "answer": last_answer,
            "transcript": transcript,
            "iterations": iterations,
            "model": model,
            "error": f"{type(exc).__name__}: {exc}",
        }
    return {
        "answer": last_answer,
        "transcript": transcript,
        "iterations": iterations,
        "model": model,
    }
